services:
  app:
    volumes: []
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  nginx:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M

  db:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  redis:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M

  reverb:
    volumes: []
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
